# Generated by Django 3.1.3 on 2021-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productimage', models.ImageField(default='', upload_to='practice/images')),
                ('name', models.CharField(max_length=150)),
                ('customerid', models.IntegerField(max_length=150)),
            ],
        ),
    ]
